---
- hosts: terraform_ansible
  user: ubuntu
  become: true
  gather_facts: no
  tasks: 
  - name: Install python3 e virtualenv
    ansible.builtin.apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes