---
- hosts: terraform_ansible
  user: ubuntu
  become: true
  gather_facts: no
  tasks: 
  - name: Install NGINX
    ansible.builtin.package:
      name: nginx
      state: present
      
  - name: Criando index.html
    copy:
      dest: /var/www/html/index.html
      content: <h1> Feito com Terraform e Ansible!</h1>