---
- hosts: terraform_ansible
  user: ubuntu  
  gather_facts: no
  tasks: 
  - name: Install python3 e virtualenv
    ansible.builtin.apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: true
  - name: Instalando dependências com pip (Django e Django rest)
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
      - django
      - djangorestframework