---
- hosts: terraform_ansible
  user: ubuntu  
  gather_facts: no
  tasks: 
  - name: Install python3 e virtualenv
    ansible.builtin.apt:
      pkg:
      - python3
      - virtualenv
      update_cache: yes
    become: true
  - name: Instalando dependências com pip (Django e Django rest)
    pip:
      virtualenv: /home/ubuntu/tcc/venv
      name:
      - django
      - djangorestframework
  - name: Iniciando o projeto
    shell: '. ~/tcc/venv/bin/activate;django-admin startproject setup ~/tcc/'
  - name: Alterando o hosts
    ansible.builtin.lineinfile:
      path: ~/tcc/setup/settings.py
      regexp: 'ALLOWED_HOSTS'
      line: 'ALLOWED_HOSTS = ["*"]'
      backrefs: yes